
import type { Property, Area, Testimonial, Blog, Award, SellerTestimonial } from './types';

export const properties: Property[] = [
  {
    id: 'prop-1',
    name: 'Emaar Beachfront Studio',
    type: 'Studio',
    category: 'Apartment',
    purpose: 'Buy',
    status: 'Off-plan',
    price: 'AED 1.2M',
    bedrooms: 0,
    bathrooms: 1,
    areaSqFt: 450,
    imageId: 'property-1',
    location: 'Emaar Beachfront',
    description: 'A stunning studio apartment in the vibrant Emaar Beachfront, offering breathtaking sea views and access to a private beach. Perfect for young professionals or as a high-yield investment.',
    amenities: ['Private Beach Access', 'Swimming Pool', 'Gym', 'Covered Parking', '24/7 Security'],
    galleryImageIds: ['gallery-1', 'gallery-2', 'gallery-3', 'gallery-4', 'gallery-5'],
    agent: {
      name: 'John Doe',
      avatarId: 'author-1',
      title: 'Senior Consultant',
      company: 'DEVELOP Real Estate',
      orn: '12345',
      propertyCount: 152,
    },
    priceNumeric: 1200000
  },
  {
    id: 'prop-2',
    name: 'Creek Harbour Villas',
    type: 'Villa',
    category: 'Villa',
    purpose: 'Buy',
    status: 'Off-plan',
    price: 'AED 8.5M',
    bedrooms: 4,
    bathrooms: 5,
    areaSqFt: 4500,
    imageId: 'property-2',
    location: 'Dubai Creek Harbour',
    description: 'An exquisite 4-bedroom villa in the heart of Dubai Creek Harbour, blending contemporary design with traditional Arabian touches. Features a private garden and stunning views of the creek.',
    amenities: ['Private Garden', 'Swimming Pool', 'Maids Room', 'Covered Parking', 'Waterfront Views'],
    galleryImageIds: ['gallery-5', 'gallery-1', 'gallery-2', 'gallery-3', 'gallery-4'],
    agent: {
      name: 'Elvira Sharshenalieva',
      avatarId: 'agent-2',
      title: 'CEO',
      company: 'EVA Real Estate LLC',
      orn: '25800',
      propertyCount: 377,
    },
    priceNumeric: 8500000
  },
  {
    id: 'prop-3',
    name: 'The Palm Royal Penthouse',
    type: 'Penthouse',
    category: 'Penthouse',
    purpose: 'Buy',
    status: 'Ready',
    price: 'AED 25M',
    bedrooms: 5,
    bathrooms: 6,
    areaSqFt: 7200,
    imageId: 'property-3',
    location: 'Palm Jumeirah',
    description: 'This ultra-luxurious penthouse on Palm Jumeirah offers 360-degree views of the Arabian Gulf and Dubai skyline. Fully furnished with bespoke interiors and a private rooftop pool.',
    amenities: ['Private Rooftop Pool', 'Full Sea View', 'Concierge', 'Private Cinema', 'Smart Home System'],
    galleryImageIds: ['gallery-2', 'gallery-3', 'gallery-1', 'gallery-5', 'gallery-4'],
    agent: {
      name: 'Alex Johnson',
      avatarId: 'author-1',
      title: 'Luxury Specialist',
      company: 'DEVELOP Real Estate',
      orn: '12345',
      propertyCount: 78,
    },
    priceNumeric: 25000000
  },
  {
    id: 'prop-4',
    name: 'Downtown Views II',
    type: 'Apartment',
    category: 'Apartment',
    purpose: 'Buy',
    status: 'Ready',
    price: 'AED 4.1M',
    bedrooms: 3,
    bathrooms: 3,
    areaSqFt: 1750,
    imageId: 'property-5',
    location: 'Downtown Dubai',
    description: 'A modern 3-bedroom apartment with direct views of the Burj Khalifa and The Dubai Fountain. Located in the bustling heart of Downtown Dubai, steps away from Dubai Mall.',
    amenities: ['Burj Khalifa View', 'Shared Gym', 'Swimming Pool', 'Direct Mall Access', 'High-speed Elevators'],
    galleryImageIds: ['gallery-3', 'gallery-1', 'gallery-4', 'gallery-2', 'gallery-5'],
    agent: {
      name: 'Emily Chen',
      avatarId: 'author-2',
      title: 'Downtown Specialist',
      company: 'DEVELOP Real Estate',
      orn: '12345',
      propertyCount: 95,
    },
    priceNumeric: 4100000
  },
  {
    id: 'prop-5',
    name: 'Arabian Ranches III - Joy',
    type: 'Townhouse',
    category: 'Townhouse',
    purpose: 'Buy',
    status: 'Ready',
    price: 'AED 2.8M',
    bedrooms: 3,
    bathrooms: 4,
    areaSqFt: 2100,
    imageId: 'property-4',
    location: 'Arabian Ranches III',
    description: 'A family-friendly 3-bedroom townhouse in the sought-after Joy community of Arabian Ranches III. Features a spacious layout, private garden, and access to world-class amenities.',
    amenities: ['Private Garden', 'Community Park', 'Swimming Pool', 'Gated Community', 'Pet Friendly'],
    galleryImageIds: ['gallery-4', 'gallery-5', 'gallery-1', 'gallery-2', 'gallery-3'],
    agent: {
      name: 'John Doe',
      avatarId: 'author-1',
      title: 'Senior Consultant',
      company: 'DEVELOP Real Estate',
      orn: '12345',
      propertyCount: 152,
    },
    priceNumeric: 2800000
  },
  {
    id: 'prop-6',
    name: 'District One Villa',
    type: 'Villa',
    category: 'Villa',
    purpose: 'Buy',
    status: 'Ready',
    price: 'AED 15M',
    bedrooms: 5,
    bathrooms: 6,
    areaSqFt: 8000,
    imageId: 'property-6',
    location: 'Mohammed Bin Rashid City',
    description: 'A luxurious 5-bedroom villa in MBR City\'s exclusive District One. This home boasts a contemporary design, high-end finishes, a private pool, and views of the Crystal Lagoon.',
    amenities: ['Crystal Lagoon Access', 'Private Pool', 'Private Cinema', 'Maids Room', 'Landscaped Garden'],
    galleryImageIds: ['gallery-1', 'gallery-2', 'gallery-5', 'gallery-3', 'gallery-4'],
    agent: {
      name: 'Jane Smith',
      avatarId: 'author-2',
      title: 'Villa Specialist',
      company: 'DEVELOP Real Estate',
      orn: '12345',
      propertyCount: 110,
    },
    priceNumeric: 15000000
  },
  {
    id: 'prop-7',
    name: 'Business Bay Office Space',
    type: 'Office',
    category: 'Commercial',
    purpose: 'Rent',
    status: 'Ready',
    price: 'AED 250,000/year',
    bedrooms: 0,
    bathrooms: 1,
    areaSqFt: 2000,
    imageId: 'property-9',
    location: 'Business Bay',
    description: 'A fully-fitted office space in a prime Business Bay tower. Features an open-plan layout, panoramic city views, and access to executive meeting rooms.',
    amenities: ['Fitted', 'High-speed Elevators', 'Concierge', 'Covered Parking', 'Canal View'],
    galleryImageIds: ['gallery-2', 'gallery-1', 'gallery-4', 'gallery-5', 'gallery-3'],
    agent: {
      name: 'Michael Brown',
      avatarId: 'author-3',
      title: 'Commercial Specialist',
      company: 'DEVELOP Commercial',
      orn: '54321',
      propertyCount: 45,
    },
    priceNumeric: 250000
  },
  {
    id: 'prop-8',
    name: 'JVC 1-Bedroom for Rent',
    type: 'Apartment',
    category: 'Apartment',
    purpose: 'Rent',
    status: 'Ready',
    price: 'AED 85,000/year',
    bedrooms: 1,
    bathrooms: 2,
    areaSqFt: 850,
    imageId: 'property-7',
    location: 'Jumeirah Village Circle',
    description: 'A modern and spacious 1-bedroom apartment in a new building in JVC. Features a large balcony, modern kitchen, and access to a rooftop pool and gym.',
    amenities: ['Shared Pool', 'Shared Gym', 'Covered Parking', 'Pet Friendly', 'Balcony'],
    galleryImageIds: ['gallery-3', 'gallery-2', 'gallery-1', 'gallery-4', 'gallery-5'],
    agent: {
      name: 'Sarah Wilson',
      avatarId: 'author-4',
      title: 'Rental Expert',
      company: 'DEVELOP Rentals',
      orn: '67890',
      propertyCount: 210,
    },
    priceNumeric: 85000
  }
];

export const areaGuides: Area[] = [
  { id: 'area-1', name: 'Dubai Marina', yield: '6.5% Avg. Yield', imageId: 'area-marina' },
  { id: 'area-2', name: 'Dubai Hills Estate', yield: '5.8% Avg. Yield', imageId: 'area-hills' },
  { id: 'area-3', name: 'Downtown Dubai', yield: '7.2% Avg. Yield', imageId: 'area-downtown' },
  { id: 'area-4', name: 'Palm Jumeirah', yield: '5.5% Avg. Yield', imageId: 'area-palm' },
];

export const testimonials: Testimonial[] = [
  {
    id: 'test-1',
    name: 'Alex Johnson',
    quote: 'The professionalism and market knowledge of the DEVELOP team were exceptional. They found our dream home in record time.',
    imageId: 'testimonial-1',
  },
  {
    id: 'test-2',
    name: 'Samantha Lee',
    quote: 'An absolutely seamless experience from start to finish. Their property management service is second to none.',
    imageId: 'testimonial-2',
  },
  {
    id: 'test-3',
    name: 'Rashid Al Maktoum',
    quote: 'As an investor, DEVELOP provides unparalleled insights and access to exclusive off-market deals. Highly recommended.',
    imageId: 'testimonial-3',
  },
];

export const sellerTestimonials: SellerTestimonial[] = [
  {
    id: 'seller-1',
    name: 'David & Sarah Johnson',
    property: 'Villa in Arabian Ranches',
    quote: 'Selling our family home was an emotional process, but the DEVELOP team handled it with incredible sensitivity and professionalism. Their valuation was spot-on, and they secured a buyer faster than we ever expected.',
    avatarFallback: 'DS',
  },
  {
    id: 'seller-2',
    name: 'Fatima Al-Marzooqi',
    property: 'Apartment in Downtown Dubai',
    quote: 'As a first-time seller, I was nervous. DEVELOP\'s data-driven approach gave me confidence. Their marketing reach is phenomenal, and the quality of offers we received was a testament to their expertise.',
    avatarFallback: 'FA',
  },
  {
    id: 'seller-3',
    name: 'Chen Wei',
    property: 'Portfolio of 3 Units',
    quote: 'I needed to liquidate part of my property portfolio quickly. DEVELOP\'s team provided a clear strategy, managed the entire process flawlessly, and exceeded my financial goals. True professionals.',
    avatarFallback: 'CW',
  },
  {
    id: 'seller-4',
    name: 'Robert Smith',
    property: 'Penthouse in Dubai Marina',
    quote: 'The attention to detail was impeccable. From the professional photography to the qualified buyer screenings, every step was handled with the utmost care. I wouldn\'t trust anyone else with a high-value asset.',
    avatarFallback: 'RS',
  },
  {
    id: 'seller-5',
    name: 'Elena Petrova',
    property: 'Off-plan unit in Emaar Beachfront',
    quote: 'DEVELOP helped me sell my off-plan property before handover. Their understanding of the secondary market for off-plan is unmatched, and they made a complex transaction feel simple.',
    avatarFallback: 'EP',
  },
  {
    id: 'seller-6',
    name: 'The Miller Family',
    property: 'Townhouse in Dubai Hills',
    quote: 'We were impressed by the global reach. Our property was marketed to investors we could never have reached on our own, resulting in a fantastic sale price. Thank you, DEVELOP!',
    avatarFallback: 'MF',
  },
];

export const blogPosts: Blog[] = [
  {
    id: 'blog-1',
    readTime: '5 min read',
    title: 'Dubai Loop Tunnel Set to Serve 80% of The City’s Population',
    excerpt: 'The visionary project aims to revolutionize urban mobility in Dubai, connecting key districts with a high-speed transit network.',
    author: {
      name: 'John Doe',
      avatarId: 'author-1',
    },
    imageId: 'blog-1',
  },
  {
    id: 'blog-2',
    readTime: '7 min read',
    title: 'Top 5 Most Expensive Villas in Dubai in 2024',
    excerpt: 'A deep dive into the most opulent and sought-after villa properties that are setting new benchmarks in luxury living.',
    author: {
      name: 'Jane Smith',
      avatarId: 'author-2',
    },
    imageId: 'blog-2',
  },
  {
    id: 'blog-3',
    readTime: '4 min read',
    title: 'The Rise of Branded Residences: A New Era of Luxury',
    excerpt: 'Explore the growing trend of branded residences and why they represent a compelling investment opportunity in Dubai.',
    author: {
      name: 'Alex Johnson',
      avatarId: 'author-1',
    },
    imageId: 'blog-3',
  },
  {
    id: 'blog-4',
    readTime: '6 min read',
    title: 'How to Secure a Mortgage in Dubai as an Expat',
    excerpt: 'A comprehensive guide to navigating the mortgage process in Dubai for non-residents looking to invest in property.',
    author: {
      name: 'Emily Chen',
      avatarId: 'author-2',
    },
    imageId: 'blog-4',
  },
];

export const awards: Award[] = [
  {
    id: 'award-1',
    title: 'Top Real Estate Agency 2023',
    description: 'Awarded by the Dubai Real Estate Institute for outstanding sales and customer satisfaction.',
    imageId: 'award-1',
  },
  {
    id: 'award-2',
    title: 'Excellence in Luxury Properties',
    description: 'Recognized for our exceptional portfolio and service in the high-end market segment.',
    imageId: 'award-2',
  },
  {
    id: 'award-3',
    title: 'Innovation in PropTech',
    description: 'Awarded for our data-driven platform and use of technology to enhance client experience.',
    imageId: 'award-3',
  },
  {
    id: 'award-4',
    title: 'Best Property Management Firm',
    description: 'For delivering market-leading returns and service quality in property management.',
    imageId: 'award-4',
  }
];
